### ISSUE TITLE
Plugin is not working.

### ISSUE THREAD

**Issue by Taswert** [KarlOfDuty/CustomLoadouts#10]
This plugin does not give out items.
The only error in console: **System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies.**

CONFIG FILE:
```
verbose: true
debug: true
delay: 0

customloadouts:
    director:
        all:
            - 100:
                - COIN 
                - COIN
                - COIN
                - COIN
```
P.S. The "Director" role exists on my server

**Comment by KarlOfDuty** [comment]
You don't have the dependency loaded

**Comment by Taswert** [comment]
This is very strange because I installed them.
![Снимок](https://user-images.githubusercontent.com/70364736/91583180-898b5000-e99c-11ea-90ad-e06fecc2b784.PNG)

**Comment by KarlOfDuty** [comment]
Doesn't seem like it's loading correctly then, try replacing it or something.

**Comment by Taswert** [comment]
Ok, I copied Newtonsoft in sm_plugins and there is no error at all, but items is still not given out.

**Comment by KarlOfDuty** [comment]
Ok, then turn on verbose and debug in the config and it will tell you why.

**Comment by Taswert** [comment]
Ehm... it was enabled already

**Comment by KarlOfDuty** [comment]
ok, then please post your full logs from startup to when a player joins
